### PR TITLE
feat: 更新web端视频操作播放合集相关接口

### LINKED ISSUE #380: 对于 `api.bilibili.com/x/web-interface/archive/has/like` 的补充
<https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/like_coin_fav.md#判断视频是否被点赞双端>

这一 API 实际上只能判断出视频**在近期内**是否被点赞，并不能判断出视频是否被点赞。「近期」的定义不明，但至少半年前点赞过的视频，用这一接口获取到结果就已经是 `0` 了。

实际上这一问题日常使用B站也能观察出来，点开一个很久之前点赞过的视频，会发现其点赞按钮并没有亮起，尝试再次点赞会提示「已点赞操作失败」之类的话语，也无法将点赞取消。

~写取消点赞脚本时研究出来的，路过的有兴趣的可以一用：[B站点赞批量取消](https://greasyfork.org/zh-CN/scripts/445754)~

### LINKED ISSUE #707: api描述错误
在`https://api.bilibili.com/x/space/wbi/acc/info`的返回值中，data字段中live_room字段的roomid字段描述应该为直播间号而不是直播间短号

### LINKED ISSUE #945: [补充] 视频合集与列表
#367 
#404 
[合集视频]-https://api.bilibili.com/x/polymer/space/seasons_archives_list?mid=37737161&sort_reverse=false&season_id=1227671&page_num=1&page_size=30
[只获取系列视频]--https://api.bilibili.com/x/polymer/web-space/home/seasons_series?mid=37737161&page_num=1&page_size=10
[查询系列视频]--https://api.bilibili.com/x/series/series?series_id=2800548

### LINKED ISSUE #1062: [更新请求] web端上报视频播放心跳接口变动
### 提交前请确认

- [X] 我已检索仓库中文档，不包含所提及内容，或所提及内容在本仓库中存在错误，且 Issues、Pull Requests 中无相关提交

### API 来源

Web 端（含 h5）

### API 类型

REST

### API 地址

https://api.bilibili.com/x/click-interface/web/heartbeat

### 详情描述

[上报视频播放心跳（web端）](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/video/report.md#%E4%B8%8A%E6%8A%A5%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%BF%83%E8%B7%B3web%E7%AB%AF) 该接口正在今日一次之测试中, 发现并未按预期工作. 使用 Firefox 开发者工具抓包发现该接口请求参数大量变动. 该问题将在最新一次 PR 由本人解决<s>(如果不出意外的话)</s>.
图片
图片

### PR DESCRIPTION
**Pull request by SessionHu**
This PR update some APIs about videos playing, operating and series/seasons.

May close some issues and help users understand some special usages.

- [d1a4f6d](https://github.com/SocialSisterYi/bilibili-API-collect/pull/1064/commits/d1a4f6dd2b4e5d57188d56671b1dfacc299ea3fd) close #1062 ~by myself~
- [ff450a6](https://github.com/SocialSisterYi/bilibili-API-collect/pull/1064/commits/ff450a65693dbdc3c9a78a05c67ddbc1a783a532) add Wbi API
- [b3c3fce](https://github.com/SocialSisterYi/bilibili-API-collect/pull/1064/commits/b3c3fce1646e72985e46492224554ba8b505849a) close #707 
- [fa6c9c8](https://github.com/SocialSisterYi/bilibili-API-collect/pull/1064/commits/fa6c9c8f575a617f6603935b5a77c9624dd5b9fb) new method of `buvid3` & `b_nut` from #790
- [45755b0](https://github.com/SocialSisterYi/bilibili-API-collect/pull/1064/commits/45755b01d8d9593d50658de83322dd79e7b45e21#diff-1a8d1ba142e61d01fd3b24620847ca2f2ff93f880973ea1e1d71de79d0123096R133) close #380
- [45755b0](https://github.com/SocialSisterYi/bilibili-API-collect/pull/1064/commits/45755b01d8d9593d50658de83322dd79e7b45e21#diff-1a8d1ba142e61d01fd3b24620847ca2f2ff93f880973ea1e1d71de79d0123096R542) add details in #244
- [1c5b778](https://github.com/SocialSisterYi/bilibili-API-collect/pull/1064/commits/1c5b7788f717f92a0e3f655e947db49e842f80e0) - [85e8fc5](https://github.com/SocialSisterYi/bilibili-API-collect/pull/1064/commits/85e8fc5304d94ccb7480545e38201219b71370ad) close #945 

<s>*ps: There are more issues I may close in the future, so it is only a draft.*</s>

### CODE REVIEW

**Comment by SessionHu** [comment]
- [b3c3fce](https://github.com/SocialSisterYi/bilibili-API-collect/pull/1064/commits/b3c3fce1646e72985e46492224554ba8b505849a) close #707 
+ [fa6c9c8](https://github.com/SocialSisterYi/bilibili-API-collect/pull/1064/commits/fa6c9c8f575a617f6603935b5a77c9624dd5b9fb) new method of `buvid3` & `b_nut` from #790

**Comment by SessionHu** [comment]
- [45755b0](https://github.com/SocialSisterYi/bilibili-API-collect/pull/1064/commits/45755b01d8d9593d50658de83322dd79e7b45e21#diff-1a8d1ba142e61d01fd3b24620847ca2f2ff93f880973ea1e1d71de79d0123096R133) close #380
- [45755b0](https://github.com/SocialSisterYi/bilibili-API-collect/pull/1064/commits/45755b01d8d9593d50658de83322dd79e7b45e21#diff-1a8d1ba142e61d01fd3b24620847ca2f2ff93f880973ea1e1d71de79d0123096R542) add details in #244

**Comment by SessionHu** [comment]
- [ ] https://api.bilibili.com/x/polymer/space/seasons_archives_list
- [ ] https://api.bilibili.com/x/polymer/web-space/home/seasons_series
- [ ] https://api.bilibili.com/x/series/series
- [ ] https://api.bilibili.com/x/polymer/web-space/seasons_series_list
- [ ] https://api.bilibili.com/x/series/archives

**Comment by xiaoyv404** [comment]
只有第一个 comment 的 close 才会生效，请移动到第一个 comment

**Comment by SessionHu** [comment]
The main reason for opening this PR has been completed. It can now be merged. But more commits may be added before merging.

**Review by z0z0r4 — APPROVED** [review]

**Comment by z0z0r4** [comment]
好久没看到这么猛的哥们了，BAC前景大好（

**Review by xiaoyv404 — APPROVED** [review]

**Comment by xiaoyv404** [comment]
那 merge 咯？

**Comment by SessionHu** [comment]
ok

**Comment by xiaoyv404** [comment]
草 deploy failed

**Comment by SessionHu** [comment]
好像是写示例的时候有个 element 忘关了...

**Comment by xiaoyv404** [comment]
> 好像是写示例的时候有个 element 忘关了... 是 2 个 qwq

麻烦你开个新 pr 修一下吧

**Comment by SessionHu** [comment]
下个短链的 PR 顺便修, 单独开有点浪费资源...

**Pull request merged**
