### PR TITLE
feat: 各种接口补充与错误修正

### PR DESCRIPTION
**Pull request by SessionHu**
- [X] <s> 6c18802 Unclosed XML tags *2 (Deploy failed) </s>
- [ ] 778219a #979
- [ ] 7f4eb13 #922
- [X] ce663be #1067
- [X] 12ed2f5 - 5efbf14 #92
- [X] df5fd8e #620 <s>(B站前后端哪里有问题怎么直播有3个查IP的接口)</s>
- [X] a8ac641 #343
- [X] 717f5cb #341
- [X] 4698cb4 907f21c 合并重复与补充未链接的接口 #1072
- [X] 4f2d2b6 #708 
- [X] 375a59d #198 <s>(麻烦以后删旧接口的时候确认一下还能不能用)</s>
- [X] 33fd444 c28c01d #548 
- [X] 72fa59c #801 
- [X] 619e948 #656 
- [X] d4041a4 #648 
- [X] bb6171c bili_ticket JavaScript (Node.js) implementation
- [X] d8716b9 #671 
- [X] b227b02 客服消息心跳与文件上传
- [x] 130cbc0 new video playing report api?
- [x] cd055bc 播放反馈
- [x] c52c745 wbi_key in bili_ticket
- [x] cebf906 /x/web-interface/search/square
- [x] e959e7e 折叠失效的 /archive_stat/stat #753
- [x] 43e178b #307 
- [x] b2dd854 #482 
- [x] d0979f9 #1080
- [x] ac09d14 #208 
- [x] e8831cf #528 
- [x] b0d5c69 /x/space/navnum
- [x] a3ac2db /x/activity/page/list
- [x] d74cd09 #701 #1075 
- [x] 9ca5a31 #1082
- [x] eb33aeb #700 #545
- [x] 05a69fe #606 
- [x] 576bf3a /paywallet/wallet/getUserWallet
- [x] 0cc8395 #1083
- [x] 7272768 #425
- [x] 5bf90ca /xlive/open-interface/v1/rtc/getTimestamp
- [x] eed7c95 #745
- [x] 89ed825 /x/polymer/web-dynamic/v1/feed/all
- [x] 8068eb5 #220
- [x] 8555082 gethistory from cv8186413

### CODE REVIEW

**Comment by SessionHu** [comment]
即使有些信息没有得到充分的补充, 但我认为目前 commit 的所有内容已经足够. 且上一次 PR 中导致 deploy failed 的原因本次 PR 中已解决, 就此而言, 该 PR 已经可以准备合并.

**Comment by SessionHu** [comment]
Now is time to review and merge this PR. I will not add commits to this PR any more if unnecessary. 1722734029

**Comment by xiaoyv404** [comment]
wait a second

**Comment by xiaoyv404** [comment]
(((( 一个pr修了太多问题了，github直接罢工

**Review by xiaoyv404 — APPROVED** [review]

**Review by xiaoyv404 — APPROVED** [review]

**Comment by SessionHu** [comment]
好耶, 由于 5cb9df4 导致的冲突而无法直接合并!

**Comment by SocialSisterYi** [comment]
> 好耶, 由于 [5cb9df4](https://github.com/SocialSisterYi/bilibili-API-collect/commit/5cb9df427eccf3992661c3ab2a7f9d255dd89c72) 导致的冲突而无法直接合并!

稍等，我 resolve 一下

**Comment by SessionHu** [comment]
It is really a pity that this PR was not merged before last week (UTC+8). No commit will be added any more. Of course, no more photos sent in QQ groups.

**Review by SocialSisterYi — APPROVED** [review]

**Comment by SessionHu** [comment]
Although this PR was merged successfully after a few days ago, many issues fixed or added in this PR was not closed. I thinks it is necessay to check them again.
I have no spare time these days (the reasons are in my Bilibili), but I will do the things I have said when I am free..

**Pull request merged**
